Repository kmgowda/SBK, pull requests merged in 2022-03, with the labels that each got.

#317 Updated build.gradle
  driver-jdbc/build.gradle
Labels: sodacode2022, SODALOW

#321 Updated build.gradle
  driver-jdbc/build.gradle
Labels: sodacode2022, SODALOW

#324 Creating new PR for Upgrading Kafka Client version
  driver-kafka/build.gradle
  driver-kafka/src/main/java/io/sbk/Kafka/Kafka.java
Labels: #SODALOW, sodacode2022

#328 Upgrade MySQL Connector/J from 8.0.22 to 8.0.28(latest)
  driver-jdbc/build.gradle
Labels: sodacode2022, SODALOW

#337 Add SBK driver for performance benchmarking of H2 database
  build-drivers.gradle
  driver-h2/build.gradle
  driver-h2/src/main/java/io/sbk/H2/H2.java
  driver-h2/src/main/resources/H2.properties
  driver-jdbc/build.gradle
  driver-jdbc/src/main/java/io/sbk/Jdbc/Jdbc.java
  settings-drivers.gradle
Labels: sodacode2022, SODAMED

#341 Added OpenIO and MinIO results in sample/charts.
  samples/charts/OpenIO_read_benchmarks.csv
  samples/charts/OpenIO_write_benchmarks.csv
  samples/charts/minio_read_benchmarks.csv
  samples/charts/minio_write_benchmarks.csv
  samples/charts/openio_minio_reader_results.xlsx
  samples/charts/openio_minio_writer_results.xlsx
Labels: sodacode2022, SODAMED
